<?php

declare(strict_types=1);

use App\Modules\Academic\Domain\AcademicYear\Models\AcademicYear;
use App\Modules\Enrollment\Domain\Registration\Models\Registration;
use App\Modules\Journal\Domain\Logbook\Models\Logbook;
use App\Modules\Program\Domain\Internship\Models\Internship;
use App\Modules\Setting\Models\Setting;
use App\Modules\User\Models\User;
use Database\Seeders\AcademicYearSeeder;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use Tests\Support\DummyData;

uses(LazilyRefreshDatabase::class);

beforeEach(function (): void {
    $this->seed(AcademicYearSeeder::class);
});

describe('3UOZP: dummy:seed and dummy:rollback console commands', function (): void {
    test('dummy:seed fails when application is not installed', function (): void {
        Setting::updateOrCreate(
            ['key' => 'setup.is_installed'],
            ['value' => false, 'group' => 'setup', 'type' => 'boolean'],
        );

        $exitCode = Artisan::call('dummy:seed');

        expect($exitCode)->toBe(1)
            ->and(Artisan::output())->toContain((string) __('dummy.not_installed'));
    });

    test('dummy:rollback fails when application is not installed', function (): void {
        Setting::updateOrCreate(
            ['key' => 'setup.is_installed'],
            ['value' => false, 'group' => 'setup', 'type' => 'boolean'],
        );

        $exitCode = Artisan::call('dummy:rollback');

        expect($exitCode)->toBe(1)
            ->and(Artisan::output())->toContain((string) __('dummy.rollback_not_installed'));
    });

    test('dummy:seed populates dummy records with prefixed IDs and prints summary', function (): void {
        $exitCode = Artisan::call('dummy:seed');

        expect($exitCode)->toBe(0);

        $output = Artisan::output();
        expect($output)->toContain((string) __('dummy.complete'))
            ->and($output)->toContain('admin@example.com');

        $prefix = (string) config('dummy.id_prefix', 'd0000000-');
        $dummyUsers = User::where('id', 'like', "{$prefix}%")->get();

        expect($dummyUsers)->not->toBeEmpty();

        $adminUser = User::where('email', 'admin@example.com')->first();
        expect($adminUser)->not->toBeNull()
            ->and(str_starts_with($adminUser->id, $prefix))->toBeTrue()
            ->and(DummyData::isDummyId($adminUser->id))->toBeTrue();
    });

    test('dummy:rollback purges dummy records and preserves base data', function (): void {
        // Create an authentic user without dummy prefix
        $realUser = User::factory()->create([
            'email' => 'real-admin@example.com',
            'username' => 'realadmin',
        ]);

        expect(DummyData::isDummyId($realUser->id))->toBeFalse();

        Artisan::call('dummy:seed');

        $prefix = (string) config('dummy.id_prefix', 'd0000000-');
        expect(User::where('id', 'like', "{$prefix}%")->count())->toBeGreaterThan(0);

        $exitCode = Artisan::call('dummy:rollback');

        expect($exitCode)->toBe(0);

        $output = Artisan::output();
        expect($output)->toContain((string) __('dummy.rollback_complete'))
            ->and($output)->toContain((string) __('dummy.rollback_summary_header'));

        // All dummy users purged
        expect(User::where('id', 'like', "{$prefix}%")->count())->toBe(0)
            ->and(User::where('email', 'admin@example.com')->exists())->toBeFalse();

        // Real user and base academic year preserved
        expect(User::where('id', $realUser->id)->exists())->toBeTrue()
            ->and(AcademicYear::count())->toBeGreaterThan(0);
    });

    test('dummy:rollback purges user-created records affiliated with dummy data', function (): void {
        Artisan::call('dummy:seed');

        // 1. Create a real student (normal UUID, non-dummy)
        $realStudent = User::factory()->create([
            'email' => 'real-student@example.com',
            'username' => 'realstudent',
        ]);
        expect(DummyData::isDummyId($realStudent->id))->toBeFalse();

        // 2. Real student registers to dummy internship
        $dummyInternship = Internship::firstOrFail();
        $realRegistration = Registration::create([
            'id' => (string) Str::uuid(), // Normal UUID generated by app
            'student_id' => $realStudent->id,
            'internship_id' => $dummyInternship->id,
            'status' => 'active',
        ]);
        expect(DummyData::isDummyId($realRegistration->id))->toBeFalse();

        // 3. Create a normal logbook for real student under this dummy internship
        $normalLogbook = Logbook::create([
            'id' => (string) Str::uuid(), // Normal UUID generated by app
            'user_id' => $realStudent->id,
            'registration_id' => $realRegistration->id,
            'date' => now()->toDateString(),
            'content' => 'Normal daily logbook entry submitted via web app',
            'status' => 'submitted',
        ]);
        expect(DummyData::isDummyId($normalLogbook->id))->toBeFalse();

        // 4. Dummy demo student submits an additional logbook with normal UUID
        $dummyStudent = User::where('email', 'student1@example.com')->firstOrFail();
        $dummyRegistration = Registration::where('student_id', $dummyStudent->id)->firstOrFail();
        $dummyStudentLogbook = Logbook::create([
            'id' => (string) Str::uuid(), // Normal UUID generated by app during demo
            'user_id' => $dummyStudent->id,
            'registration_id' => $dummyRegistration->id,
            'date' => now()->subDay()->toDateString(),
            'content' => 'Another logbook created by demo user',
            'status' => 'draft',
        ]);
        expect(DummyData::isDummyId($dummyStudentLogbook->id))->toBeFalse();

        // Run rollback
        $exitCode = Artisan::call('dummy:rollback');
        expect($exitCode)->toBe(0);

        // Assert: The affiliated records are deleted
        expect(Registration::where('id', $realRegistration->id)->exists())->toBeFalse()
            ->and(Logbook::where('id', $normalLogbook->id)->exists())->toBeFalse()
            ->and(Logbook::where('id', $dummyStudentLogbook->id)->exists())->toBeFalse();

        // Assert: The real student account remains intact in the system
        expect(User::where('id', $realStudent->id)->exists())->toBeTrue();
    });

    test('dummy:rollback handles empty state gracefully', function (): void {
        $exitCode = Artisan::call('dummy:rollback');

        expect($exitCode)->toBe(0);

        $output = Artisan::output();
        expect($output)->toContain((string) __('dummy.rollback_none'));
    });

    test('dummy:seed and dummy:rollback can run in production environment when installed', function (): void {
        app()['env'] = 'production';

        $seedExit = Artisan::call('dummy:seed');
        expect($seedExit)->toBe(0)
            ->and(Artisan::output())->toContain((string) __('dummy.complete'));

        $rollbackExit = Artisan::call('dummy:rollback');
        expect($rollbackExit)->toBe(0)
            ->and(Artisan::output())->toContain((string) __('dummy.rollback_complete'));

        app()['env'] = 'testing';
    });
});
